apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: main
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "20m"
        sidecar.istio.io/proxyCPULimit: "100m"
        sidecar.istio.io/proxyMemory: "48Mi"
        sidecar.istio.io/proxyMemoryLimit: "128Mi"
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
