apiVersion: v1
kind: ResourceQuota
metadata:
  name: boutique-quota
  namespace: boutique
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 8Gi
    pods: "40"
    services: "20"
