apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    gcpsm:
      projectID: project-19d98bfe-795f-49b8-af0
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: kfounding-dev
          serviceAccountRef:
            name: argocd-external-secrets
