# Enables Istio traffic-management and security resources for the boutique application.
# This component includes mTLS, authorization policies, frontend routing, and mesh metrics.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - allow-egress-googleapis.yaml
  - frontend-gateway.yaml
  - frontend.yaml
  - mtls.yaml
  - istio-podmonitor.yaml
  - frontend-authorization-policy.yaml
  - productcatalogservice-authorization-policy.yaml
  - recommendationservice-authorization-policy.yaml
  - cartservice-authorization-policy.yaml
  - currencyservice-authorization-policy.yaml
  - checkoutservice-authorization-policy.yaml
  - paymentservice-authorization-policy.yaml
  - emailservice-authorization-policy.yaml
  - shippingservice-authorization-policy.yaml
  - redis-cart-authorization-policy.yaml
