# Enables Istio traffic-management and security resources for the boutique application.
# This component includes mTLS, authorization policies, frontend routing, and mesh metrics.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - allow-egress-googleapis.yaml
  - frontend-gateway.yaml
  - frontend.yaml
  - mtls.yaml
  - istio-podmonitor.yaml
  - authorization-policy.yaml
  - recommendationservice-fault-injection.yaml
