namespace: logging

agent:
  name: logging-agent
  version: "9.2.0"

elasticsearchRef:
  name: elasticsearch

tolerations:
  - operator: Exists

resources:
  requests:
    cpu: 20m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 700Mi
