namespace: logging

agent:
  name: logging-agent
  version: "9.2.0"

elasticsearchRef:
  name: elasticsearch

tolerations:
  - operator: Exists

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Overridden by env/dev/values.yaml or env/prod/values.yaml.
environment: default

kibana:
  dashboardProvisioning:
    enabled: false

  serviceName: ""
  namespace: logging

  authSecret:
    name: elasticsearch-es-elastic-user
    key: elastic

  dataView:
    id: kubernetes-container-logs-default
    title: logs-kubernetes.container_logs-default

  dashboard:
    title: Boutique Application Logs - DEFAULT
