apiVersion: v1
kind: ResourceQuota
metadata:
  name: boutique-quota
  namespace: boutique
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "40"
    limits.memory: 50Gi
    pods: "75"
    services: "20"
