apiVersion: v1
kind: ResourceQuota
metadata:
  name: boutique-quota
  namespace: boutique
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "30"
    limits.memory: 40Gi
    pods: "50"
    services: "20"
