apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ai-model-config-patch.yaml
  - path: ai-bootstrap-model-config-patch.yaml
  - path: ai-ollama-resources-patch.yaml
