tempo:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability-dev

  tempo:
    nodeSelector:
      cloud.google.com/gke-nodepool: platform-observability-dev

opentelemetry-collector:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability-dev

  config:
    exporters:
      otlp:
        endpoint: tracing-dev-tempo.tracing.svc.cluster.local:4317
        tls:
          insecure: true

tracing:
  samplingPercentage: 100
