tempo:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability

  tempo:
    nodeSelector:
      cloud.google.com/gke-nodepool: platform-observability

opentelemetry-collector:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability
