tempo:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability-dev

  tempo:
    nodeSelector:
      cloud.google.com/gke-nodepool: platform-observability-dev

opentelemetry-collector:
  nodeSelector:
    cloud.google.com/gke-nodepool: platform-observability-dev
