apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-health-report-dev
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: release/v3.0.1-multi-env-validation
    path: argocd/apps/dev/argocd-health-report
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
