apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-dev
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: develop
    path: argocd/apps/argo-rollouts-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
