apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator-dev
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform

  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.1.0
    helm:
      releaseName: elastic-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
