apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-agent-dev
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform

  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: develop
    path: helm-chart/logging-agent
    helm:
      valueFiles:
        - values.yaml
        - env/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
