apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: Platform apps like observability, logging, tracing and operators

  sourceRepos:
    - https://github.com/linux-cnf/microservices-demo.git
    - https://helm.elastic.co
    - https://charts.external-secrets.io
    - https://istio-release.storage.googleapis.com/charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: elastic-system-dev
    - server: https://kubernetes.default.svc
      namespace: monitoring-dev
    - server: https://kubernetes.default.svc
      namespace: logging-dev
    - server: https://kubernetes.default.svc
      namespace: tracing-dev
    - server: https://kubernetes.default.svc
      namespace: external-secrets-dev
    - server: https://kubernetes.default.svc
      namespace: argocd-dev
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: istio-system-dev
    - server: https://kubernetes.default.svc
      namespace: ai
  
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: boutique
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: Online Boutique application

  sourceRepos:
    - https://github.com/linux-cnf/microservices-demo.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: boutique-dev

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
