apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: boutique
  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: release/v3.0.1-multi-env-validation
    path: kustomize/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
