apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: develop
    path: helm-chart/tracing
    helm:
      valueFiles:
        - values.yaml
        - env/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
