apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""

    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end

    return hs

  resource.customizations.health.elasticsearch.k8s.elastic.co_Elasticsearch: |
    hs = {}
    hs.status = "Progressing"
    hs.message = "Waiting for Elasticsearch health"

    if obj.status ~= nil then
      if obj.status.health == "green" then
        hs.status = "Healthy"
        hs.message = "Elasticsearch cluster health is green"
        return hs
      end

      if obj.status.health == "yellow" then
        hs.status = "Healthy"
        hs.message = "Elasticsearch cluster health is yellow but accepted for test single-node environment"
        return hs
      end

      if obj.status.health == "red" then
        hs.status = "Degraded"
        hs.message = "Elasticsearch cluster health is red"
        return hs
      end
    end

    return hs
