apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../argo-rollouts

patches:
  - path: argo-rollouts-dev-patch.yaml
  - path: argo-rollouts-dev-pdb-patch.yaml
  - path: argo-rollouts-servicemonitor-dev-patch.yaml
