apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    gcpsm:
      projectID: project-9e0b2bd9-4649-487c-9d1
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: kfounding
          serviceAccountRef:
            name: argocd-external-secrets
