apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    iam.gke.io/gcp-service-account: external-secrets-gsm@project-9e0b2bd9-4649-487c-9d1.iam.gserviceaccount.com
