apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: https://github.com/linux-cnf/microservices-demo.git
    targetRevision: main
    path: argocd/apps/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/target/deletionPolicy
