apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: Platform apps like observability, logging, tracing and operators

  sourceRepos:
    - https://github.com/linux-cnf/microservices-demo.git
    - https://helm.elastic.co
    - https://charts.external-secrets.io

  destinations:
    - server: https://kubernetes.default.svc
      namespace: elastic-system
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: logging
    - server: https://kubernetes.default.svc
      namespace: tracing
    - server: https://kubernetes.default.svc
      namespace: external-secrets
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
  
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: boutique
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: Online Boutique application

  sourceRepos:
    - https://github.com/linux-cnf/microservices-demo.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: boutique

  clusterResourceWhitelist: []

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
