environment: dev

grafanaDashboards:
  enabled: true

  boutiqueServiceTraffic:
    enabled: true
    namespace: boutique
    folder: Boutique Dev

  boutiqueTracing:
    enabled: true
    namespace: boutique
    folder: Boutique Dev

  boutiqueTracingOverview:
    enabled: true
    namespace: boutique
    folder: Boutique Dev

  boutiqueServiceTrafficOverview:
    enabled: true
    namespace: boutique
    folder: Boutique Dev

  kubernetesPlatformHealth:
    enabled: true
    folder: Platform Dev
    namespace: boutique

  distributedTracingOperations:
    enabled: true
    namespace: boutique
    folder: Boutique Dev

kube-prometheus-stack:
  grafana:
    additionalDataSources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tracing-dev-tempo.tracing.svc.cluster.local:3200
        isDefault: false
        jsonData:
          nodeGraph:
            enabled: true
          serviceMap:
            datasourceUid: prometheus
          search:
            hide: false
