# Must be overridden by values-dev.yaml or values-prod.yaml.
environment: default

namespaces:
  monitoring: monitoring
  logging: logging

kube-prometheus-stack:
  crds:
    enabled: true

  grafana:
    enabled: true
    defaultDashboardsEnabled: true

    service:
      type: ClusterIP

    ingress:
      enabled: false

    additionalDataSources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.tracing.svc.cluster.local:3200
        isDefault: false

    nodeSelector:
      workload: observability

    tolerations:
      - key: dedicated
        operator: Equal
        value: observability
        effect: NoSchedule

  prometheus:
    enabled: true

    service:
      type: ClusterIP

    ingress:
      enabled: false

    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      enableRemoteWriteReceiver: true

      nodeSelector:
        workload: observability

      tolerations:
        - key: dedicated
          operator: Equal
          value: observability
          effect: NoSchedule

  alertmanager:
    enabled: true

    service:
      type: ClusterIP

    ingress:
      enabled: false

    alertmanagerSpec:
      nodeSelector:
        workload: observability

      tolerations:
        - key: dedicated
          operator: Equal
          value: observability
          effect: NoSchedule

  kube-state-metrics:
    enabled: true

    nodeSelector:
      workload: observability

    tolerations:
      - key: dedicated
        operator: Equal
        value: observability
        effect: NoSchedule

  prometheus-node-exporter:
    enabled: true

    tolerations:
      - operator: Exists

grafanaDashboards:
  enabled: true

  boutiqueServiceTraffic:
    enabled: true
    namespace: boutique
    folder: Boutique

  boutiqueTracing:
    enabled: true
    namespace: boutique
    folder: Boutique
