apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    iam.gke.io/gcp-service-account: external-secrets-gsm@project-19d98bfe-795f-49b8-af0.iam.gserviceaccount.com
