# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0

name: "Clean up deployment"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to clean up"
        required: true

jobs:
  cleanup-namespace:
    runs-on: ubuntu-latest

    steps:
      - name: Delete PR namespace in staging cluster
        if: ${{ always() }}
        timeout-minutes: 20
        env:
          PROJECT_ID: "online-boutique-ci"
          PR_CLUSTER: "prs-gke-cluster"
          REGION: "us-central1"
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
          gcloud container clusters get-credentials "${PR_CLUSTER}" \
            --region "${REGION}" \
            --project "${PROJECT_ID}"

          NAMESPACE="pr${PR_NUMBER}"

          kubectl delete namespace "${NAMESPACE}"
